export const clientsDatas = [
	{
		id: 0,
		firstName: 'Lolita',
		lastName: 'Weaver',
		address: '856 Keen Court, Maxville, Kansas, 5865',
	},
	{
		id: 1,
		firstName: 'Betsy',
		lastName: 'Garner',
		address: '643 Ruby Street, Jackpot, Alaska, 1639',
	},
	{
		id: 2,
		firstName: 'Helena',
		lastName: 'Rasmussen',
		address: '106 Chestnut Avenue, Takilma, Virginia, 9147',
	},
	{
		id: 3,
		firstName: 'Burks',
		lastName: 'Dudley',
		address: '166 Landis Court, Jacksonburg, Maine, 3129',
	},
	{
		id: 4,
		firstName: 'Krista',
		lastName: 'Dejesus',
		address: '495 Voorhies Avenue, Tryon, Massachusetts, 9789',
	},
	{
		id: 5,
		firstName: 'Burke',
		lastName: 'Wilson',
		address: '296 Stewart Street, Lupton, New Mexico, 8321',
	},
	{
		id: 6,
		firstName: 'Salas',
		lastName: 'Vincent',
		address: '581 Channel Avenue, Kenwood, Kentucky, 4474',
	},
	{
		id: 7,
		firstName: 'Wolfe',
		lastName: 'Rowland',
		address: '643 Caton Avenue, Graball, District Of Columbia, 7561',
	},
	{
		id: 8,
		firstName: 'Lilly',
		lastName: 'Nelson',
		address: '687 Sedgwick Street, Frizzleburg, Maryland, 1689',
	},
	{
		id: 9,
		firstName: 'Pollard',
		lastName: 'Ellison',
		address: '689 Kosciusko Street, Eagletown, Nebraska, 9342',
	},
	{
		id: 10,
		firstName: 'Erma',
		lastName: 'Wolf',
		address: '460 Vanderbilt Street, Irwin, Palau, 405',
	},
	{
		id: 11,
		firstName: 'Theresa',
		lastName: 'Whitaker',
		address: '783 Losee Terrace, Aguila, Wisconsin, 7733',
	},
	{
		id: 12,
		firstName: 'Pitts',
		lastName: 'Klein',
		address: '710 Pierrepont Street, Alfarata, Virgin Islands, 7889',
	},
	{
		id: 13,
		firstName: 'Mabel',
		lastName: 'Gilmore',
		address: '426 Albee Square, Derwood, Florida, 6438',
	},
	{
		id: 14,
		firstName: 'Eugenia',
		lastName: 'Burt',
		address: '615 Mill Road, Hollymead, Wyoming, 7054',
	},
	{
		id: 15,
		firstName: 'Watts',
		lastName: 'Hampton',
		address: '808 Gotham Avenue, Edmund, American Samoa, 6429',
	},
	{
		id: 16,
		firstName: 'Lucia',
		lastName: 'Crane',
		address: '379 Clarendon Road, Shasta, Minnesota, 7268',
	},
	{
		id: 17,
		firstName: 'Lila',
		lastName: 'Lester',
		address: '413 Rodney Street, Cuylerville, Marshall Islands, 2791',
	},
	{
		id: 18,
		firstName: 'Green',
		lastName: 'Mcintyre',
		address: '749 Dewitt Avenue, Driftwood, Michigan, 5396',
	},
	{
		id: 19,
		firstName: 'Kellie',
		lastName: 'Chen',
		address: '448 Arlington Place, Venice, Ohio, 2776',
	},
];
